import { IUser } from '../models/user.interface';
export const users: IUser[] = [
  {
    id: 1,
    name: 'Juan',
    nickname: 'Juancho',
    email: 'correo1@correo.com',
    password: '123',
    country: 'Argentina',
    state: 'Buenos Aires',
    city: 'Buenos Aires',
    reputation: 3,
  },
  {
    id: 2,
    name: 'Pedro',
    nickname: 'Pepito',
    email: 'correo2@correo.com',
    password: '123',
    country: 'Argentina',
    state: 'Santa Fe',
    city: 'Rosario',
    reputation: 5,
  },
  {
    id: 3,
    name: 'Pablo',
    nickname: 'Pablito',
    email: 'correo3@correo.com',
    password: '123',
    country: 'Argentina',
    state: 'Córdoba',
    city: 'Córdoba',
    reputation: 4,
  },
  {
    id: 4,
    name: 'Luis',
    nickname: 'Luisito',
    email: 'correo4@correo.com',
    password: '123',
    country: 'Argentina',
    state: 'Buenos Aires',
    city: 'La Plata',
    reputation: 2,
  },
];
